source "https://rubygems.org"

gemspec

group :test do
  case ENV['RAILS_VERSION']
  when '4.2'
    gem 'activesupport', '~> 4.2.11'
  when '5.0'
    gem 'activesupport', '~> 5.0.7'
  when '5.1'
    gem 'activesupport', '~> 5.1.7'
  when '5.2'
    gem 'activesupport', '~> 5.2.5'
  when '6.0'
    gem 'activesupport', '~> 6.0.3'
  else
    gem 'activesupport', '~> 6.1.3'
  end

  gem 'monetize'
  gem 'rspec'
end

platforms :jruby do
  group :ci do
    gem 'rspec_junit_formatter'
  end
end
